"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vyk&360pu3!vp2vxqc@#5-_81(2i^_y6djeczq)jcaqz^cvq83'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',

     'corsheaders',
     'cloudinary',

      'cloudinary_storage',
    'api'
]




REST_FRAMEWORK = {
        'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),         
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # This should be at the top of the list
    

    'django.middleware.common.CommonMiddleware',
]
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

# Optional: Allow specific headers



CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # Add your frontend URL
]


import cloudinary

cloudinary.config(
    cloud_name="daalfrqob",  # your cloud name
    api_key="428318487815239",  # your API key
    api_secret="6qL3HdWcb3HJ72iqIGnDMRkVNd8"  # your API secret
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'daalfrqob',
    'API_KEY': '428318487815239',
    'API_SECRET': '6qL3HdWcb3HJ72iqIGnDMRkVNd8',
}


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


MEDIA_URL = 'https://res.cloudinary.com/daalfrqob/'




ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


STATIC_URL = '/static/'

# Use an external service like AWS S3 or Railway's static file hosting for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 



import os
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from the .env file

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),        # DB name from environment variable
        'USER': os.getenv('DB_USER'),        # DB user from environment variable
        'PASSWORD': os.getenv('DB_PASSWORD'), # DB password from environment variable
        'HOST': os.getenv('DB_HOST'),        # DB host from environment variable (Railway provides this)
        'PORT': os.getenv('DB_PORT', '3306'), # Default MySQL port (3306)
    }
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
 #   'default': {
  #      'ENGINE': 'django.db.backends.mysql',
   #     'NAME': 'artcase',
    #    'USER': 'root',
     #   'PASSWORD': 'h-3-7.3.1009',
      #  'HOST': 'localhost',  # Or your MySQL server IP
       # 'PORT': '3306',  # Default MySQL port
    #}
#} ###############################################################################################################################

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



AUTH_USER_MODEL = 'api.CustomUser'

# settings.py
#import os

# Media files configuration
#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Add other necessary settings


# Printful API settings
# settings.py
from decouple import config

# Load API keys from environment variables
PRINTFUL_API_KEY = config('PRINTFUL_API_KEY')
PRINTFUL_SECRET_KEY = config('PRINTFUL_SECRET_KEY')  # If you plan to use this key



ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '.railway.app', 
    '2c24-156-203-218-172.ngrok-free.app'
]



# In settings.py
import os
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

#PRINTFUL_API_TOKEN = os.getenv('PRINTFUL_API_TOKEN')  # Access the token




# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
